package com.chainsleuth.data.entity;

/**
 * Enumeration of statutory legal documents and regulatory notices generated by ChainSleuth.
 * <p>
 * Supports automated document compilation using Thymeleaf templates and PDF rendering engines.
 * Documents intended for judicial presentation or statutory summons require verifiable law
 * enforcement officer signatures to satisfy formal procedural codes.
 * </p>
 *
 * <ul>
 *   <li><b>Phase:</b> Phase 2A — Relational Data Layer &amp; Persistence Infrastructure</li>
 *   <li><b>Platform Component:</b> Legal Document Classification</li>
 *   <li><b>Interacts with:</b> {@link LegalDocumentEntity}</li>
 * </ul>
 */
public enum DocumentType {

    /**
     * Comprehensive forensic brief prepared to support First Information Report (FIR) registration.
     */
    FIR_BRIEF("Forensic FIR Brief", false, "fir_brief"),

    /**
     * Formal summons and document production notice issued under Section 91 of the Bharatiya Nagarik Suraksha Sanhita (BNSS).
     */
    SECTION_91_NOTICE("BNSS Section 91 Production Notice", true, "section91_notice"),

    /**
     * Electronic record admissibility certificate mandated under Section 65B of the Indian Evidence Act.
     */
    SECTION_65B_CERT("Section 65B Evidence Certificate", true, "section65b_cert"),

    /**
     * Urgent asset preservation and wallet freezing request directed to a Virtual Asset Service Provider (VASP).
     */
    EXCHANGE_FREEZING_REQ("Exchange Account Freeze Request", false, "exchange_freezing_req"),

    /**
     * General statutory inquiry or intelligence requisition notice served to a cryptocurrency exchange.
     */
    EXCHANGE_NOTICE("Exchange Inquiry Notice", false, "exchange_notice"),

    /**
     * Structured forensic brief formatted specifically for magistrate court evidentiary submissions.
     */
    COURT_SUBMISSION("Magistrate Court Submission", true, "court_submission");

    private final String displayName;
    private final boolean requiresOfficerSignature;
    private final String templateName;

    /**
     * Constructs a legal document type constant.
     *
     * @param displayName              human-readable document title
     * @param requiresOfficerSignature true if an authorized law enforcement officer signature is required
     * @param templateName             underlying Thymeleaf template resource identifier
     */
    DocumentType(String displayName, boolean requiresOfficerSignature, String templateName) {
        this.displayName = displayName;
        this.requiresOfficerSignature = requiresOfficerSignature;
        this.templateName = templateName;
    }

    /**
     * Retrieves the human-readable document title.
     *
     * @return document title
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Indicates whether the document requires a formal officer digital signature.
     *
     * @return {@code true} if officer signature is mandatory; {@code false} otherwise
     */
    public boolean requiresOfficerSignature() {
        return requiresOfficerSignature;
    }

    /**
     * Retrieves the Thymeleaf template filename corresponding to this document type.
     *
     * @return template filename without file extension
     */
    public String getTemplateName() {
        return templateName;
    }
}
