package com.chainsleuth.data.audit;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.MappedSuperclass;
import java.time.Instant;
import java.util.UUID;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Abstract mapped superclass providing standardized audit metadata for all persistent domain entities.
 * <p>
 * <b>MappedSuperclass vs. Entity:</b><br>
 * Unlike an entity annotated with {@code @Entity}, a class annotated with {@link MappedSuperclass}
 * does not correspond to a standalone database table and cannot be queried directly via polymorphic
 * JPQL. Instead, its structural and audit mapping definitions are inherited down the class hierarchy,
 * contributing columns directly to the concrete subclass tables (such as the {@code cases} table).
 * This eliminates schema boilerplate while preserving strict relational table independence.
 * </p>
 * <p>
 * <b>Temporal Accuracy with {@link Instant}:</b><br>
 * All timestamps are recorded using {@link Instant} rather than {@link java.time.LocalDateTime}.
 * {@link Instant} designates a precise, monotonic moment along the universal timeline (UTC epoch).
 * In distributed blockchain forensics involving law enforcement agencies across multiple international
 * jurisdictions, timezone-agnostic UTC representation is critical to prevent clock skew, daylight
 * saving ambiguities, and legal admissibility challenges under electronic evidence discovery rules.
 * </p>
 * <p>
 * <b>Operator Identity via {@link UUID}:</b><br>
 * The {@link CreatedBy} and {@link LastModifiedBy} annotations evaluate to {@link UUID}, matching
 * the identity tokens generated by Supabase Auth and extracted via {@link ChainSleuthAuditorAware}.
 * By retaining the user UUID rather than a username or email string, forensic audit trails remain
 * immutable even if an investigator's email address or display name changes over time.
 * </p>
 *
 * <ul>
 *   <li><b>Phase:</b> Phase 2A — Relational Data Layer &amp; Persistence Infrastructure</li>
 *   <li><b>Platform Component:</b> Central Audit Superclass</li>
 *   <li><b>Interacts with:</b> {@link ChainSleuthAuditorAware}, {@link AuditingEntityListener}</li>
 * </ul>
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class AuditableEntity {

    /**
     * Point in time when this entity was first persisted to the relational database.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    protected Instant createdAt;

    /**
     * Point in time when this entity was last modified and committed to the database.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    protected Instant updatedAt;

    /**
     * Unique identifier of the authenticated operator who created this entity.
     * Nullable for system-initiated tasks or automated background migrations.
     */
    @CreatedBy
    @Column(name = "created_by_user_id", nullable = true, updatable = false)
    protected UUID createdByUserId;

    /**
     * Unique identifier of the authenticated operator who last updated this entity.
     * Nullable for system-initiated updates or automated tasks.
     */
    @LastModifiedBy
    @Column(name = "last_modified_by_user_id", nullable = true)
    protected UUID lastModifiedByUserId;

    /**
     * Protected no-arg constructor required by the Jakarta Persistence specification and Hibernate proxies.
     */
    protected AuditableEntity() {
    }

    /**
     * Retrieves the UTC creation timestamp.
     *
     * @return creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Retrieves the UTC last modification timestamp.
     *
     * @return last modified timestamp
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Retrieves the identifier of the user who created this entity.
     *
     * @return creator user UUID, or {@code null} if created in an unauthenticated or system context
     */
    public UUID getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * Retrieves the identifier of the user who last modified this entity.
     *
     * @return last modifier user UUID, or {@code null} if modified in an unauthenticated or system context
     */
    public UUID getLastModifiedByUserId() {
        return lastModifiedByUserId;
    }
}
